language: node_js
node_js:
  - '12'
install: 
  - npm install
services: 
  - postgresql
before_script:
  - psql -c 'create database iguru_test;' -U postgres
script: 
  - npm test
after_success:
  - npm run coverage
notifications:
  email: false